### ISSUE TITLE
Plotting fbranch z-scores

### ISSUE THREAD

**Issue by RishiDeKayne** [millanek/Dsuite#44]
Hi Dsuite team,
I am trying to plot the fbranch statistics as well as the corresponding z-scores using the dtools.py script (as in your Malawi cichlid manuscript).

When I do this just with the fbranch statistic as follows:
```
Dsuite Fbranch ./collapsed_tree_no_bootstraps_rotated.txt out_combined_tree.txt > fbranch_collapsed.txt"
../Dsuite/utils/dtools.py fbranch_collapsed.txt ./collapsed_tree_no_bootstraps_rotated.txt
```
It works great and the heatmap is outputted (although without indication of fb statistical significance). However, when I try to use the combined output that includes the z-scores :
```
#using combined fbranch/z-score output
Dsuite Fbranch -Z ./collapsed_tree_no_bootstraps_rotated.txt out_combined_tree.txt > fbranch_collapsed_z.txt"
../Dsuite/utils/dtools.py fbranch_collapsed_z.txt ./collapsed_tree_no_bootstraps_rotated.txt

#or with only the extracted z-scores
../Dsuite/utils/dtools.py z_scores.txt ./collapsed_tree_no_bootstraps_rotated.txt
```
I get the following error:
```
Traceback (most recent call last):
  File "/data/martin/genomics/analyses/Danaus_genome/Dchry2/test/../Dsuite/utils/dtools.py", line 3654, in <module>
    sys.exit(main())
  File "/data/martin/genomics/analyses/Danaus_genome/Dchry2/test/../Dsuite/utils/dtools.py", line 3624, in main
    fb[fb<0] = 0
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/arraylike.py", line 40, in __lt__
    return self._cmp_method(other, operator.lt)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/frame.py", line 6854, in _cmp_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/frame.py", line 6893, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 325, in apply
    applied = b.apply(f, **kwargs)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 381, in apply
    result = func(self.values, **kwargs)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/ceph/users/rdekayne/.conda/envs/dsuite/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '<' not supported between instances of 'str' and 'int'
```

I'm not sure if the script was intended to add the significance dots as in your paper (apologies if not) but any advice about what I might be doing wrong or parsing the z-scores correctly would be greatly appreciated,
All the best,
Rishi De-Kayne

[collapsed_tree_no_bootstraps_rotated.txt](https://github.com/millanek/Dsuite/files/7490973/collapsed_tree_no_bootstraps_rotated.txt)
[fbranch_collapsed_z.txt](https://github.com/millanek/Dsuite/files/7490974/fbranch_collapsed_z.txt)
[fbranch_collapsed.txt](https://github.com/millanek/Dsuite/files/7490975/fbranch_collapsed.txt)
[z_scores.txt](https://github.com/millanek/Dsuite/files/7490985/z_scores.txt)

**Comment by RishiDeKayne** [comment]
Not exactly a solution to auto-plotting but if anyone else comes across this and wants to do the same the best way I have found so far is the following:

In bash:
```
#get fbranch stats and z-scores
Dsuite Fbranch -Z ./collapsed_tree_no_bootstraps_rotated.txt out_combined_tree.txt > fbranch_collapsed_z.txt"
#extract just z-scores (your line count will vary)
tail -n 69 fbranch_collapsed_z.txt > z_scores.txt
```
  
In R:
```
#read in z-scores
zscores <- read.csv("z_scores.txt", sep = "\t")

header <- zscores[,1:2]
             
scores <- zscores[,3:ncol(zscores)]

#replace values < 3 with 0 and >=3 with 0.99 - leave nan values as they are
newscores <- as.data.frame(c())
for(i in 1:nrow(scores)){
  for(j in 1:ncol(scores)){
    if(scores[i,j] != 'NaN'){
      if(as.numeric(scores[i,j])<3){
        newscores[i,j] <- 0
      }
      if(as.numeric(scores[i,j])>=3){
        newscores[i,j] <- 0.99
      }
    }
    if(scores[i,j] == 'NaN'){
      newscores[i,j] <- "nan"
    }
  }
}

all_new <- cbind(header, newscores)

colnames(all_new) <- colnames(zscores)

#write to new file
write.csv(all_new, "all_new_zscore.txt", quote=FALSE, row.names=FALSE)
```

Then in bash again:
```
#get rid of 'X' in header from read.csv 
sed -i 's/X//g' all_new_zscore.txt
#make heatmap plot
../Dsuite/utils/dtools.py all_new_zscore.txt ./collapsed_tree_no_bootstraps_rotated.nwk
cp fbranch.png fbranch_zscore_binary.png
cp fbranch.svg fbranch_zscore_binary.svg
```
