### ISSUE TITLE
cannot plot fbranch statistics

### ISSUE THREAD

**Issue by bnsacks** [millanek/Dsuite#54]
This is a fantastic set of tools.  However, I am hitting a snag I cannot seem to solve.  I can run 

.../Dsuite Fbranch -Z Allprunedr2-50thinned100.nex.partsroot2.txt SETS_tree-guided_tree.txt > fbranch1.txt

and I get the file with lots of values and 'nan's
but then when I try the next command:

.../utils/dtools.py fbranch1.txt Allprunedr2-50thinned100.nex.partsroot2.txt

I get the following error:

Traceback (most recent call last):
  File "/home/yote/bin/Dsuite/utils/dtools.py", line 3654, in <module>
    sys.exit(main())
  File "/home/yote/bin/Dsuite/utils/dtools.py", line 3624, in main
    fb[fb<0] = 0
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/arraylike.py", line 48, in __lt__
    return self._cmp_method(other, operator.lt)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/frame.py", line 6934, in _cmp_method
    new_data = self._dispatch_frame_op(other, op, axis=axis)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/frame.py", line 6973, in _dispatch_frame_op
    bm = self._mgr.apply(array_op, right=right)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/internals/managers.py", line 302, in apply
    applied = b.apply(f, **kwargs)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/internals/blocks.py", line 402, in apply
    result = func(self.values, **kwargs)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/ops/array_ops.py", line 283, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/yote/.local/lib/python3.9/site-packages/pandas-1.4.2-py3.9-linux-x86_64.egg/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '<' not supported between instances of 'str' and 'int'

The files are attached below:
[Allprunedr2-50thinned100.nex.partsroot2.txt](https://github.com/millanek/Dsuite/files/8953690/Allprunedr2-50thinned100.nex.partsroot2.txt)
[SETS_tree-guided_tree.txt](https://github.com/millanek/Dsuite/files/8953673/SETS_tree-guided_tree.txt)
[fbranch1.txt](https://github.com/millanek/Dsuite/files/8953674/fbranch1.txt)

**Comment by ACColin** [comment]
Hi, have you found a solution to this problem? I'm having the same issue. Thanks!

**Comment by bnsacks** [comment]
No, I gave up on it, but would still be interested if you find a solution.

**Comment by ACColin** [comment]
Right. so I think we found the solution, at least it work for our data and looking at your 'fbranch1.txt' file it should work for yours as well.
If you selected the -z option with the Fbranch command, you get the Z-scores added in the final Fbranch.txt file.
However it seems that the dtools script is meant to parse data without the Z-scores and will try to parse those as well if included in the input file therefore throwing an error.
You can either rerun without adding the optional -z flag, or remove the Z-scores from the in file to avoid it.
This should do :) hope it helps. Cheers

**Comment by bnsacks** [comment]
Fantastic! Thank you.  I will save your comment where i left off and try this when I am able to get back to it.  Cheers!

**Comment by rturba** [comment]
Hello,

I'm also having issues plotting the Fbranch stats, but I get a different error. I think that might be a python error, but I'm not familiar with it so I'm not sure how it relates to the program. Has anyone seen this happen? And what would that mean for my Fbranch file?

`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (72,) + inhomogeneous part.`

[Fbranch file](https://drive.google.com/file/d/1sOVaTo_0QFnvaMb32wOVeAcM0h3i_Ipb/view?usp=share_link)

Thank you!

**Comment by xuefenfei712** [comment]
Hello rturba

I have the same issue as you, I even run again the Dtrios, do you have a soulution?

Best
Xuexue

**Comment by rturba** [comment]
> I still haven't solved the problem, and you? At 2023-05-30 22:05:06, "xuefenfei712" ***@***.***> wrote: Hello rturba I have the same issue as you, I even run again the Dtrios, do you have a soulution? Best Xuexue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hi, there! So sorry for not replying with a solution earlier. I've discovered that the python environment where I had installed DSuite was the problem. For sure some version incompatibility.  Just running the plot command outside of my virtual environment with python3 worked fine. Try checking the python version you're using and try with another one. I hope that helps!

**Comment by yangwukaidi** [comment]
Ok, I'll follow your advice. Best wishes to you!
















At 2023-09-06 02:08:14, "rturba" ***@***.***> wrote:

I still haven't solved the problem, and you? At 2023-05-30 22:05:06, "xuefenfei712" @.> wrote: Hello rturba I have the same issue as you, I even run again the Dtrios, do you have a soulution? Best Xuexue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

Hi, there! So sorry for not replying with a solution earlier. I've discovered that the python environment where I had installed DSuite was the problem. For sure some version incompatibility. Just running the plot command outside of my virtual environment with python3 worked fine. Try checking the python version you're using and try with another one. I hope that helps!

**Comment by yefanglee** [comment]
hello!
I have a new errow in plotting fbranch, like this:
>python3 Dsuite/utils/dtools.py fbranch.txt nwk.txt
Traceback (most recent call last):
  File "/home/lingjiang/liyf/china_analyses/dsuit/Dsuite/utils/dtools.py", line 3654, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lingjiang/liyf/china_analyses/dsuit/Dsuite/utils/dtools.py", line 3629, in main
    fb1, tree_no_outgroup = align_fbranch_with_tree(fb, tree,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingjiang/liyf/china_analyses/dsuit/Dsuite/utils/dtools.py", line 3465, in align_fbranch_with_tree
    fb = fb.drop(outgroup, axis=1)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingjiang/anaconda3/lib/python3.11/site-packages/pandas/core/frame.py", line 5344, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/home/lingjiang/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingjiang/anaconda3/lib/python3.11/site-packages/pandas/core/generic.py", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lingjiang/anaconda3/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 7000, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['Outgroup'] not found in axis"

I tried python3.7, 3.9 and 3.11,  and pandas 1.5 and 2.1.4. they all didn't work.

**Comment by se420** [comment]
> yefanglee

Hello，yefanglee!

I have got the same issue with you. Have you figure out how to deal with it?

**Comment by athenasyarifa** [comment]
Hi everyone, 

I also had the same problem. I managed to solve it the following way: 

First, I tried running in my python environment (version 3.8.11) where I know I have pandas and matplotlib installed. And this didn't work and had the following error: 
```
Reading tree...
Traceback (most recent call last):
  File "/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2022__Pmon_pop_gen/4__wholegenome/8__dsuite/tools/Dsuite/utils/dtools.py", line 3654, in <module>
    sys.exit(main())
  File "/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2022__Pmon_pop_gen/4__wholegenome/8__dsuite/tools/Dsuite/utils/dtools.py", line 3629, in main
    fb1, tree_no_outgroup = align_fbranch_with_tree(fb, tree,
  File "/dss/dsslegfs01/pr53da/pr53da-dss-0026/projects/2022__Pmon_pop_gen/4__wholegenome/8__dsuite/tools/Dsuite/utils/dtools.py", line 3482, in align_fbranch_with_tree
    fb = fb.loc[row_order, col_order].iloc[::-1]  # ,::-1
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/indexing.py", line 1147, in _getitem_tuple
    return self._multi_take(tup)
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/indexing.py", line 1098, in _multi_take
    d = {
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/indexing.py", line 1099, in <dictcomp>
    axis: self._get_listlike_indexer(key, axis)
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/indexing.py", line 1327, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5774, in _get_indexer_strict
    keyarr = com.asarray_tuplesafe(keyarr)
  File "/dss/dsshome1/lxc0C/ra35naf/miniconda3/envs/tools/lib/python3.8/site-packages/pandas/core/common.py", line 241, in asarray_tuplesafe
    result = np.asarray(values, dtype=dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (30,) + inhomogeneous part.
```

Then, I made a new conda environment with python 3.9.15 installed (no pandas, matplotlib installed). Then I did what the installation instructions of Dsuite (dtools.py) described: 

```
cd utils
python3 setup.py install --user --prefix=
# then I have one installation error: error: Couldn't find a setup script in /dss/lxclscratch/0C/ra35naf/ra35naf/easy_install-x09xw6e8/matplotlib-3.10.0rc1.tar.gz. So I just installed this using pip:
pip install matplotlib
pip install pytz

# then run again
dtools.py --outgroup Outgroup ssp_fbranch_out.txt ./test_constree.nwk
```
And it worked! Hope it helps!

Best, 
Rifa
